### ISSUE TITLE
setMax() not working.

### ISSUE THREAD

**Issue by maxgmer** [daimajia/NumberProgressBar#39]
I have an issue. No matter if I called setMax() before, max value of my progress bar stays 100.

**Comment by maxgmer** [comment]
btw my progress bar is in RecyclerView.

**Comment by Dona278** [comment]
@maxgmer Try with https://github.com/Dona278/NumberProgressBar

**Comment by maxgmer** [comment]
@Dona278 same problem( i use progressbar.setProgress() and progressbar.setMax(). Am i right? Are there any library methods to set progress and maximum value?

**Comment by Dona278** [comment]
I think that 100 is the percentage of progressbar. The percentage shown is a proportion between current value and the max value. For example, if you set max value to 4 and current value to 2 you will see 50 on the progressbar. If you want to show a value that is different from the classic percentage you can use `.setCustomValue()`. For example if you set max value to 12 and current value to 10 you can use custom value to show 10 instead of 83 and with suffix you can add custom text like "10 level".

**Comment by maxgmer** [comment]
my setmax value is 1000, but setProgress(99) sets 99% on progress bar.

**Comment by Dona278** [comment]
Using this code:
```java
NumberProgressBar progressBar = (NumberProgressBar) findViewById(R.id.numberbar1);
progressBar.setMax(1000);
progressBar.setProgress(99);
```
I had this result:
![image](https://cloud.githubusercontent.com/assets/10567243/21783771/ff72b358-d6b8-11e6-8bc3-bdd9379dc7b1.png)

**Comment by maxgmer** [comment]
should i use the same import to use your library?

**Comment by Dona278** [comment]
From the readme of https://github.com/Dona278/NumberProgressBar, try:

**Project build.gradle**
```
allprojects {
     repositories {
         maven { url "http://dl.bintray.com/dona278/maven/" }
     }
}

```
**Module build.gradle**
```
dependencies {
   compile "com.daimajia.numberprogressbar:library:1.3@aar"
}
```
Maven repository url and version of library are changed.

**Comment by daimajia** [comment]
![image](https://cloud.githubusercontent.com/assets/2503423/23216612/87f6c2cc-f951-11e6-8bed-5f0324fa6212.png)

Due to wrong understanding of the percentage, close this issue.
